services:
  api:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    container_name: dotnet-api
    volumes:
      - .:/workspaces/fullstack-app:z
      - ./backend:/workspaces/fullstack-app/backend:z
      - ~/dotnet_docker_cache/home:/tmp/dotnet_home
      - ~/dotnet_docker_cache/nuget:/tmp/nuget_cache
      - ~/.microsoft/usersecrets:/tmp/dotnet_home/.microsoft/usersecrets
    tmpfs:
      - /tmp/build:uid=1000,gid=1000,mode=777,exec
    working_dir: /workspaces/fullstack-app/backend
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_CLI_HOME=/tmp/dotnet_home
      - NUGET_PACKAGES=/tmp/nuget_cache
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - COMPlus_EnableDiagnostics=0
    command: >
      sh -c "dotnet watch run --non-interactive"
    #sh -c "dotnet watch run --no-hot-reload --non-interactive"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: node:24-alpine
    container_name: angular-frontend
    working_dir: /app
    volumes:
      - ./frontend-angular:/app:z
      - angular_node_modules:/app/node_modules
    ports:
      - "4200:4200"
      - "4000:4000"
    command: >
      sh -c "if [ ! -d 'node_modules' ] || [ ! -f 'node_modules/.bin/ng' ]; then npm install; fi &&
             npx ng serve --host 0.0.0.0"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
  angular_node_modules:
